
servers:
  - url: http://localhost:3000/api/beggy/bag-items
    description: Local development server

tags:
  - name: Bag-Items
    description: Operations related to bags


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CsrfToken:
      type: apiKey
      in: header
      name: x-csrf-token
      description: |
        CSRF token provided and Obtain from the '/api/baggy/auth/csrf-token' endpoint, for state-changing requests. This should match the token from the server response.
    CsrfSecret:
      type: apiKey
      in: header
      name: x-csrf-secret
      description: |
        CSRF secret provided and Obtain from the '/api/baggy/auth/csrf-token' endpoint, for state-changing requests. This should match the secret from the server response.

  schemas:
    Bag:
      type: object
      required:
        - id
        - name
        - type
        - size
        - capacity
        - maxWeight
        - weight
      properties:
        id:
          type: string
          format: uuid
          description: "Unique identifier for the bag."
        name:
          type: string
          description: "Name of the bag."
        type:
          type: string
          $ref: '#/components/schemas/BagType'
          description: "Type of the bag."
        color:
          type: string
          default: "black"
          nullable: true
          description: "Color of the bag (default: black)."
        size:
          type: string
          $ref: '#/components/schemas/Size'
          description: "Size category of the bag."
        capacity:
          type: number
          format: float
          description: "Capacity of the bag in liters."
        maxWeight:
          type: number
          format: float
          description: "Maximum weight the bag can carry in kg."
        weight:
          type: number
          format: float
          description: "Weight of the bag in kg."
        material:
          type: string
          $ref: '#/components/schemas/Material'
          nullable: true
          description: "Material of the bag."
        features:
          type: array
          items:
            type: string
            $ref: '#/components/schemas/BagFeature'
          description: "List of bag features."
        createdAt:
          type: string
          format: date-time
          description: "Timestamp when the bag was created."
        updatedAt:
          type: string
          format: date-time
          description: "Timestamp when the bag was last updated."
        userId:
          type: string
          format: uuid
          nullable: true
          description: "User ID who owns this bag (nullable if unowned)."
        bagItems:
          type: array
          items:
            $ref: "#/components/schemas/BagItems"
          description: "List of items inside the bag."

    BagItems:
      type: array
      items:
        type: object
        properties:
          bagId: 
            type: string
            format: uuid
          itemId:
            type: string
            format: uuid
          bag: 
            $ref: '#/components/schemas/Bag'
          item:
            $ref: '#/components/schemas/Item'
          createdAt:
            type: string
            format: date-time
          updatedAt:
            type: string
            format: date-time
        required:
          - bagId
          - itemId
          - bag
          - item
          - createdAt
          - updatedAt
        description: Bag item entry in the database

    BagType:
      type: string
      enum:
        - BACKPACK
        - DUFFEL
        - TOTE
        - MESSENGER
        - LAPTOP_BAG
        - TRAVEL_BAG
        - HANDBAG
        - CROSSBODY
        - SHOULDER_BAG
      description: Allowed Bag Types

    BagFeature:
      type: string
      enum:
        - NONE
        - WATERPROOF
        - PADDED_LAPTOP_COMPARTMENT
        - USB_PORT
        - ANTI_THEFT
        - MULTIPLE_POCKETS
        - LIGHTWEIGHT
        - EXPANDABLE
        - REINFORCED_STRAPS
        - TROLLEY_SLEEVE
        - HIDDEN_POCKET
      description: Allowed Bag Features

    ItemCategory:
      type: string
      enum:
        - ELECTRONICS
        - ACCESSORIES
        - FURNITURE
        - MEDICINE
        - CLOTHING
        - BOOKS
        - FOOD
      description: Allowed Item Categories

    Size:
      type: string
      enum:
        - SMALL       
        - MEDIUM      
        - LARGE       
        - EXTRA_LARGE
      description: Allowed Suitcase Sizes

    Material: 
      type: string
      enum: 
        - LEATHER
        - SYNTHETIC
        - FABRIC
        - POLYESTER
        - NYLON
        - CANVAS
        - HARD_SHELL
        - METAL
      description: Allowed Suitcase Material

    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        category:
          $ref: '#/components/schemas/ItemCategory'
        quantity:
          type: integer
        weight:
          type: number
        volume:
          type: number
        color:
          type: string
        isFragile:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        userId: 
          type: string
          format: uuid
        user:
          $ref: '#/components/schemas/User'
        SuitcaseItems:
          type: object
          items:
            $ref: '#/components/schemas/Item'
        bagItems:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      required:
        - id
        - name
        - category
        - quantity
        - weight
        - volume
        - isFragile

    ItemId:
      type: object
      required:
        - itemId
      properties:
        itemId:
          type: string
          format: uuid
          description: "Unique identifier for an item."
          example: "550e8400-e29b-41d4-a716-446655440000"

    ItemsIds:
      type: object
      required:
        - itemsIds
      properties:
        itemsIds:
          type: array
          minItems: 1
          maxItems: 5
          items:
            $ref: "#/components/schemas/ItemId"

    ItemsIdsForDelete:
      type: object
      required:
        - itemsIds
        - confirmDelete
      properties:
        itemsIds:
          type: array
          minItems: 1
          maxItems: 6
          items:
            type: string
            format: uuid
            description: "Unique identifier for an item."
          example:
            - "550e8400-e29b-41d4-a716-446655440000"
            - "f47ac10b-58cc-4372-a567-0e02b2c3d479"

        confirmDelete:
          type: boolean
          description: "Confirmation flag for deleting the items."
          example: true

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        status:
          type: string
        message:
          type: string
        data:
          oneOf:
            - type: array
              items:
                type: object
                $ref: "#/components/schemas/Bag"
            - type: object
              $ref: "#/components/schemas/Bag"
        meta:
          oneOf:
            - $ref: "#/components/schemas/PaginationMeta"
            - $ref: "#/components/schemas/DeletionsMeta"
            - type: object
              additionalProperties: true
          nullable: true

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        status:
          type: string
        message:
          type: string
        error:
          type: string
        stack:
          type: string
          nullable: true

    PaginationMeta:
      type: object
      properties:
        totalCount:
          type: integer
        totalFind: 
          type: integer
        page: 
          type: integer
        limit: 
          type: integer
        offset:
          type: integer
        searchFilter:
          type: object
          properties:
            field:
              type: string
            search:
              type: string
        orderBy:
          type: object
          properties:
            field:
              type: string
            sortBy:
              type: string
            order:
              type: string
              enum:
                - asc
                - desc

    DeletionsMeta:
      type: object
      properties:
        totalCount:
          type: integer
        totalDelete:
          type: integer


paths:
  /api/beggy/bag-items/{bagId}/item:
    post:
      summary: Create an Item for User's Bag
      tags:
        - Bag-Items
      security:
        - BearerAuth: []
      parameters:
        - name: bagId
          in: path
          required: true
          schema:
            type: string
          description: ID of the bag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemId"
      responses:
        "201":
          description: Item added to the bag successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Delete an Item from User's Bag
      tags:
        - Bag-Items
      security:
        - BearerAuth: []
      parameters:
        - name: bagId
          in: path
          required: true
          schema:
            type: string
          description: ID of the bag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemId"
              description: The ID of the item to remove
      responses:
        "200":
          description: Item deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/beggy/bag-items/{bagId}/items:
    post:
      summary: Create Multiple Items for User's Bag
      tags:
        - Bag-Items
      security:
        - BearerAuth: []
      parameters:
        - name: bagId
          in: path
          required: true
          schema:
            type: string
          description: ID of the bag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemsIds"
      responses:
        "201":
          description: Items added to the bag successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Delete Multiple Items from User's Bag
      tags:
        - Bag-Items
      security:
        - BearerAuth: []
      parameters:
        - name: bagId
          in: path
          required: true
          schema:
            type: string
          description: ID of the bag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemsIdsForDelete"
      responses:
        "200":
          description: Items deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/beggy/bag-items/{bagId}/items/bulk:
    delete:
      summary: Delete All Items from User's Bag
      tags:
        - Bag-Items
      security:
        - BearerAuth: []
      parameters:
        - name: bagId
          in: path
          required: true
          schema:
            type: string
          description: ID of the bag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemsIdsForDelete"
      responses:
        "200":
          description: All items deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
